version: '2'

services:

  wordpress:
    build: ./config/docker/web
    restart: unless-stopped
    volumes:
      - ./website/:/var/www/html
    ports:
      - 8080:80
    env_file:
      - ./.env

  mysql:
    build: ./config/docker/mysql
    ports:
      - 30360:3306
    env_file:
      - ./.env

  wpcli:
    build:
        context: ./config/docker/wpcli
        dockerfile: Dockerfile
    volumes_from:
      - wordpress:rw
    links:
      - mysql:mysql