version: '3.1'

services:

  wordpress:
    build: ./config/docker/web
    restart: unless-stopped
    ports:
      - 8080:80
    env_file:
      - ./.env

  mysql:
    build: ./config/docker/mysql
    ports:
      - 30360:3306
    env_file:
      - ./.env
